const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#16A34A",
    background: "#F4F4F8",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#16A34A",
    primaryForeground: "#FFFFFF",
    secondary: "#DCFCE7",
    secondaryForeground: "#14532D",
    muted: "#F1F0F5",
    mutedForeground: "#6B7280",
    accent: "#DCFCE7",
    accentForeground: "#14532D",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#E5E7EB",
    urgent: "#EF4444",
    urgentLight: "#FEF2F2",
    urgentDark: "#DC2626",
    track: "#F59E0B",
    trackLight: "#FFFBEB",
    trackDark: "#D97706",
    remember: "#3B82F6",
    rememberLight: "#EFF6FF",
    rememberDark: "#2563EB",
    success: "#10B981",
    successLight: "#ECFDF5",
    overlay: "rgba(0,0,0,0.5)",
  },
  radius: 14,
};

export default colors;
